### ISSUE TITLE
Webhooks got error 500

### ISSUE THREAD

**Issue by strausmann** [terramar-labs/packages#74]
The Version 3.2.0 has a problem with the Webhooks after upgrade from 3.1.5.

**Comment by tyler-sommer** [comment]
Hi @strausmann,

First off, thanks for using Packages! I'm sorry to hear that you're having issues with your upgrade. I want you to know I saw your issues, and I'll set aside some time tomorrow morning (US tz) to respond properly.

Thanks for your patience.

**Comment by tyler-sommer** [comment]
Thanks for the bug report @strausmann !

Could you provide more information about your issue? If you hit a webhook URL manually, do you get a response?

Assuming you're running Packages on `127.0.0.1` and package with ID 384 is enabled:

```
curl -X POST http://127.0.0.1/webhook/384/receive
```

You should see simply "OK" if the page worked. Otherwise, you should see some error output that should be useful for us to debug.

Let me know if you have any questions. Thanks again for using Packages!

**Comment by strausmann** [comment]
OK, the issue was a moved git project. her are the display error output:

```
-bash-4.1$ curl -X POST https://mydomain.de/webhook/320/
<br />
<b>Fatal error</b>:  Uncaught Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for &quot;POST /webhook/320/&quot; in /var/www/vhos          ts/mydomain.de/httpdocs/packages/vendor/nice/framework/src/Router/RouterSubscriber.php:57
Stack trace:
#0 [internal function]: Nice\Router\RouterSubscriber-&gt;onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object          (Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#1 /var/www/vhosts/mydomain.de/httpdocs/packages/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symf          ony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#2 /var/www/vhosts/mydomain.de/httpdocs/packages/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\          EventDispatcher-&gt;doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\Ge in <b>/var/www/vhosts/mydomain.de/httpd          ocs/packages/vendor/nice/framework/src/Router/RouterSubscriber.php</b> on line <b>57</b><br />
```
Can you fix that with a error page ?

Regards,

Bjoern
