### ISSUE TITLE
Error 500: Sync GitLab Remote - Fatal error: Uncaught PDOException

### ISSUE THREAD

**Issue by strausmann** [terramar-labs/packages#78]
After click on the Sync Button for my GitLab Remote i got an Error 500.

> Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`devpackages`.`packages_gitlab_configurations`, CONSTRAINT `FK_1FE0005DF44CABFF` FOREIGN KEY (`package_id`) REFERENCES `packages` (`id`)) in /var/www/vhosts/mydomain.de/httpdocs/packages/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105 Stack trace: #0 /var/www/vhosts/mydomain.de/httpdocs/packages/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL) #1 /var/www/vhosts/mydomain.de/httpdocs/packages/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1006): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /var/www/vhosts/mydomain.de/httpdocs/packages/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(596): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM pac...', Array, Array) #3 /var/www/vhosts/mydomain.de/htt in /var/www/vhosts/mydomain.de/httpdocs/packages/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 60

**Comment by strausmann** [comment]
The Issue comes after on gitlab is a repository renamed or removed.

**Comment by tyler-sommer** [comment]
Thanks for the bug report! I thought this issue was already fixed, but apparently not!

**Comment by NeoBlack** [comment]
can confirm the issue, with the same scenario, rename or remove a repository on gitlab break sync of the complete remote. should be fixed with prio I think, because it is a breaking bug and has a big impact.

**Comment by tyler-sommer** [comment]
Agreed, this is a pretty bad issue. It looks like it's going to require a database migration or improvements in how packages are deleted.

I'll take a look at what possible solutions we have as soon as possible.

As always, thanks for your contributions @strausmann and @NeoBlack ! It's very much appreciated.

**Comment by NeoBlack** [comment]
I would recommend to add a delete flag to the model and mark the packages as "deleted", this make it possible to show this information also in the admin interface or frontend.

The information that a package is missing is very interesting, and a hard delete could be realized in the admin interface. anyway, the problem on delete is a wrong cascade definition in the database definition. Not sure where exactly, but the error message is really clear: " Integrity constraint violation"

**Comment by tyler-sommer** [comment]
Agreed on the soft delete implementation, @NeoBlack. Should have gone that way from the start. No matter what, we can handle whatever logic is necessary in a doctrine preRemove event subscriber.

**Comment by tyler-sommer** [comment]
#109 is a simple fix for now. I'd like to see a new column added (`deleted`?) that is then used to simply not show the package in the UI. Leaving this open
